version: '3.8'


services:
  api:
    container_name: api
    image: api:latest
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:9000"
    ports:
      - '9000:9000'
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
