# Generated by Django 4.1.2 on 2022-11-17 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['creation_time'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time',
            new_name='creation_time',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='companion',
        ),
        migrations.AddField(
            model_name='chat',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='chat_creation_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='chat_description'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False, verbose_name='is_this_a_group_chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='chat_name'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, null=True, verbose_name='message_id_edited_status'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, null=True, verbose_name='message_is_read_status'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=10, null=True, verbose_name='message_status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='message_author'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='message_content'),
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_time', models.DateTimeField(auto_now_add=True, verbose_name='user_invitation_in_chat_time')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='chat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Chat member',
                'verbose_name_plural': 'Chat members',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(through='chats.ChatMember', to=settings.AUTH_USER_MODEL, verbose_name='chat_users'),
        ),
    ]
