# Generated by Django 4.1.2 on 2022-11-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
