# Generated by Django 4.1.2 on 2022-11-16 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_alter_message_author_alter_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='companion',
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='chat_description'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False, verbose_name='is_this_a_group_chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='chat_name'),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='chat_users'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, null=True, verbose_name='message_id_edited_status'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, null=True, verbose_name='message_is_read_status'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=10, null=True, verbose_name='message_status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='message_content'),
        ),
    ]
