# Generated by Django 4.1.2 on 2022-11-22 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='personal_user_admin'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='is_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='is_this_user_an_admin'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='is_creator',
            field=models.BooleanField(default=False, null=True, verbose_name='is_this_user_a_creator'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='invitation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='was_invited_at'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
