# Generated by Django 4.1.2 on 2022-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_chat_last_message_remove_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=10485760, null=True, upload_to='files/', verbose_name='message_image'),
        ),
    ]
