# Generated by Django 4.1.2 on 2022-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, max_length=10485760, null=True, upload_to='files/', verbose_name='message_audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, max_length=10485760, null=True, upload_to='files/', verbose_name='message_image'),
        ),
    ]
