# Generated by Django 4.1.2 on 2022-12-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_message_audio_alter_message_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image',
            new_name='file',
        ),
    ]
