# Generated by Django 4.1.2 on 2022-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_rename_image_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=10485760, null=True, upload_to='files/', verbose_name='message_image'),
        ),
    ]
