# Generated by Django 4.1.2 on 2022-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_remove_message_file_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, max_length=10485760, null=True, upload_to='media/', verbose_name='message_audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=10485760, null=True, upload_to='media/', verbose_name='message_image'),
        ),
    ]
