# Generated by Django 4.1.2 on 2022-12-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_alter_message_audio_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.TextField(blank=True, null=True, verbose_name='message_audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='message_image'),
        ),
    ]
