# Generated by Django 4.1.3 on 2022-12-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_alter_message_audio_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='chats.message', verbose_name='chat_last_message'),
        ),
    ]
