# Generated by Django 4.1.2 on 2023-01-08 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_chat_last_message_alter_chat_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='creation_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='chat_timestamp'),
            preserve_default=False,
        ),
    ]
