# Generated by Django 4.1.3 on 2022-12-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_alter_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='chat_description'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='chat_name'),
        ),
    ]
