# Generated by Django 4.1.2 on 2022-11-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_bio_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, null=True, verbose_name='is_user_currently_online'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='user_last_online_time'),
        ),
    ]
