# Generated by Django 4.1.2 on 2023-01-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_online_user_last_seen_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_online',
            new_name='isOnline',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_seen_at',
            new_name='lastSeenAt',
        ),
    ]
