# Generated by Django 4.1.2 on 2022-11-22 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0004_delete_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='message_content')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='message_time')),
                ('status', models.CharField(max_length=10, null=True, verbose_name='message_status')),
                ('is_read', models.BooleanField(default=False, null=True, verbose_name='message_is_read_status')),
                ('is_edited', models.BooleanField(default=False, null=True, verbose_name='message_id_edited_status')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='message_author')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='chat')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['creation_time'],
            },
        ),
    ]
